"use client";

import { useMemo, useState } from "react";

type Region={id:number;name:string;state:string};
type Civ={id:number;name:string;description:string};
type Character={id:number;name:string;description:string;civilization:string;region:string;power:string;goal:string;origin:"creator"|"birth"|"npc";parents?:number[]};
type Event={id:number;day:number;text:string;impact:string};
type Consequence={id:number;due:number;text:string;impact:string};

const mapPoint=(id:number,offset=0)=>({left:12+((id+offset*37)%70),top:16+((id*7+offset*23)%62)});

export default function Home(){
 const [screen,setScreen]=useState<"home"|"create"|"world">("home");
 const [step,setStep]=useState(1);
 const [worldName,setWorldName]=useState("");
 const [theme,setTheme]=useState("Fantasy");
 const [magic,setMagic]=useState(true);
 const [day,setDay]=useState(1);
 const [tab,setTab]=useState("Carte");
 const [regions,setRegions]=useState<Region[]>([]);
 const [civs,setCivs]=useState<Civ[]>([]);
 const [chars,setChars]=useState<Character[]>([]);
 const [events,setEvents]=useState<Event[]>([]);
 const [consequences,setConsequences]=useState<Consequence[]>([]);
 const [regionName,setRegionName]=useState("");
 const [civName,setCivName]=useState("");
 const [civDescription,setCivDescription]=useState("");
 const [charName,setCharName]=useState("");
 const [charDescription,setCharDescription]=useState("");
 const [charCiv,setCharCiv]=useState("");
 const [charRegion,setCharRegion]=useState("");
 const [charPower,setCharPower]=useState("");
 const [charGoal,setCharGoal]=useState("");
 const [idea,setIdea]=useState("");
 const [responseIdea,setResponseIdea]=useState("");
 const [responseTarget,setResponseTarget]=useState("");
 const [allowNPC,setAllowNPC]=useState(false);
 const [npcName,setNpcName]=useState("");
 const [npcRole,setNpcRole]=useState("");
 const [parentA,setParentA]=useState("");
 const [parentB,setParentB]=useState("");
 const [childName,setChildName]=useState("");
 const [notice,setNotice]=useState("");

 const title=worldName||"MONDE SANS NOM";
 const log=(text:string,impact:string)=>setEvents(e=>[{id:Date.now()+Math.random(),day,text,impact},...e]);

 const createRegion=()=>{if(!regionName.trim())return;const r={id:Date.now(),name:regionName.trim(),state:"Explorée"};setRegions(x=>[...x,r]);log("La région "+r.name+" apparaît sur la carte.","Le territoire existe maintenant dans l'histoire et évoluera avec le monde.");setRegionName("");setNotice("✦ "+r.name+" apparaît immédiatement sur la carte.");};
 const createCiv=()=>{if(!civName.trim())return;const c={id:Date.now(),name:civName.trim(),description:civDescription.trim()||"Civilisation créée par le créateur."};setCivs(x=>[...x,c]);log("La civilisation "+c.name+" est fondée.","Elle peut évoluer à partir des éléments réellement présents dans le monde.");setCivName("");setCivDescription("");setNotice("♜ "+c.name+" est maintenant visible dans le monde.");};
 const createChar=()=>{if(!charName.trim())return;const c:Character={id:Date.now(),name:charName.trim(),description:charDescription.trim()||"Personnage créé par le créateur.",civilization:charCiv,region:charRegion,power:charPower,goal:charGoal||"Trouver sa place dans le monde",origin:"creator"};setChars(x=>[...x,c]);log(c.name+" entre dans le monde.","Ses conséquences ne sont pas encore connues.");if(/magie noire|ombre/i.test(c.power))setConsequences(x=>[...x,{id:Date.now()+1,due:day+2,text:"La puissance de "+c.name+" commence à déformer son environnement.",impact:"Une première conséquence apparaît seulement après l'avancée du temps."},{id:Date.now()+2,due:day+5,text:"Une catastrophe menace le monde autour de "+c.name+".",impact:"Le passé ne peut pas être supprimé : il faudra créer une influence cohérente pour répondre à cette menace."}]);setCharName("");setCharDescription("");setCharPower("");setCharGoal("");setNotice("♙ "+c.name+" apparaît immédiatement sur la carte.");};
 const createNPC=()=>{if(!allowNPC||!npcName.trim())return;const n:Character={id:Date.now(),name:npcName.trim(),description:"PNJ volontairement ajouté par le créateur.",civilization:"",region:"",power:"",goal:npcRole||"Vivre dans le monde",origin:"npc"};setChars(x=>[...x,n]);log("Le PNJ "+n.name+" entre dans le monde.","Il n'a pas été généré automatiquement : le créateur a choisi de l'ajouter.");setNpcName("");setNpcRole("");};
 const createChild=()=>{const a=chars.find(c=>String(c.id)===parentA),b=chars.find(c=>String(c.id)===parentB);if(!a||!b||a.id===b.id||!childName.trim())return setNotice("Choisis deux parents et donne un nom à l'enfant.");const c:Character={id:Date.now(),name:childName.trim(),description:"Enfant de "+a.name+" et "+b.name+".",civilization:a.civilization||b.civilization,region:a.region||b.region,power:"Héritage à découvrir",goal:"Grandir dans le monde",origin:"birth",parents:[a.id,b.id]};setChars(x=>[...x,c]);log(c.name+" naît dans le monde.","Ce personnage existe uniquement grâce à une descendance justifiée.");setChildName("");setParentA("");setParentB("");};
 const addEvent=()=>{if(!idea.trim())return;const text=idea.trim();log(text,"Cet ajout est permanent et ses conséquences seront révélées avec le temps.");setConsequences(x=>[...x,{id:Date.now(),due:day+2,text:"Le monde commence à réagir à : "+text,impact:"Une conséquence devient visible après l'avancée du temps."}]);setIdea("");setNotice("✦ L'événement entre dans la chronologie.");};
 const coherence=(text:string)=>{const t=text.toLowerCase();if(!magic&&/magie|sort|sorcier|dragon|lumière|ombre/.test(t))return {ok:false,score:8,msg:"La magie est interdite par les règles de ce monde."};if(theme==="Historique"&&/robot|laser|vaisseau|ia/.test(t))return {ok:false,score:12,msg:"Cette technologie ne correspond pas au monde historique choisi."};if(theme==="Médiéval"&&/robot|laser|vaisseau/.test(t))return {ok:false,score:25,msg:"Cette influence nécessite une explication compatible avec l'époque."};return {ok:true,score:90,msg:"Influence compatible avec les règles fondamentales du monde."};};
 const createResponse=()=>{if(!responseIdea.trim()||!responseTarget)return;const a=coherence(responseIdea);if(!a.ok)return setNotice("⚠ "+a.msg);const text=responseIdea.trim();log("Contre-influence : "+text,"Cette nouvelle cause tente de répondre à une conséquence existante.");setConsequences(x=>[...x,{id:Date.now(),due:day+1,text:"La contre-influence « "+text+" » produit ses premiers effets.",impact:"Le monde révèle si cette réponse limite, transforme ou aggrave la situation. Rien n'est effacé."}]);setResponseIdea("");setNotice("⚔ Contre-influence créée · cohérence "+a.score+"/100");};
 const advance=()=>{const next=day+1;const due=consequences.filter(c=>c.due<=next);if(due.length){setEvents(e=>[...due.map(c=>({id:c.id,day:next,text:c.text,impact:c.impact})),...e]);setConsequences(c=>c.filter(x=>x.due>next));setNotice("⏳ Le temps révèle "+due.length+" nouvelle(s) conséquence(s).");}else setNotice("⏳ Jour "+next+" · le monde continue d'évoluer.");setDay(next);};

 const stats=useMemo(()=>[{n:regions.length,l:"Régions"},{n:civs.length,l:"Civilisations"},{n:chars.length,l:"Personnages"},{n:events.length,l:"Événements"}],[regions,civs,chars,events]);

 if(screen==="home")return <main className="landing"><div className="landingGlow"/><nav><div className="brand">✦ ARTHENIS <small>WHERE WORLDS ARE BORN</small></div><button className="primary" onClick={()=>setScreen("create")}>Créer un monde</button></nav><section className="hero"><p>SIMULATEUR DE MONDES VIVANTS</p><h1>Tu écris le commencement.<br/><em>Le monde écrit la suite.</em></h1><span>Crée uniquement ce que tu veux voir exister. Observe ensuite les conséquences.</span><button className="primary big" onClick={()=>setScreen("create")}>Entrer dans Arthenis →</button></section></main>;

 if(screen==="create")return <main className="landing"><nav><div className="brand">✦ ARTHENIS <small>CRÉATION DU MONDE · {step}/4</small></div></nav><section className="creator"><div className="progress"><i style={{width:(step/4)*100+"%"}}/></div>{step===1&&<><p>PREMIÈRE ÉTAPE</p><h2>Donne naissance à ton monde.</h2><input value={worldName} onChange={e=>setWorldName(e.target.value)} placeholder="Nom du monde"/><select value={theme} onChange={e=>setTheme(e.target.value)}><option>Fantasy</option><option>Médiéval</option><option>Science-fiction</option><option>Historique</option></select></>}{step===2&&<><p>RÈGLES DE RÉALITÉ</p><h2>Définis ce qui est possible.</h2><button className={"choice "+(magic?"active":"")} onClick={()=>setMagic(!magic)}>✦ Magie {magic?"autorisée":"interdite"}</button></>}{step===3&&<><p>LOI FONDAMENTALE</p><h2>Rien n'est effacé.</h2><div className="rule">Les éléments créés deviennent une partie permanente de l'histoire. Pour changer le futur, il faut créer une nouvelle cause dans le monde.</div><div className="rule">Les personnages n'apparaissent jamais automatiquement, sauf descendance de personnages existants.</div></>}{step===4&&<><p>PRÊT À JOUER</p><h2>{title}</h2><div className="rule">{theme} · {magic?"Magie possible":"Sans magie"}<br/>Le monde commence vide. La carte affichera uniquement ce que tu ajoutes.</div></>}<div className="creatorNav"><button onClick={()=>setStep(Math.max(1,step-1))}>← Retour</button>{step<4?<button className="primary" disabled={step===1&&!worldName.trim()} onClick={()=>setStep(step+1)}>Continuer →</button>:<button className="primary" onClick={()=>setScreen("world")}>Découvrir le monde →</button>}</div></section></main>;

 const menu=[["Carte","◈"],["Chronologie","⌛"],["Ajouter","＋"],["Répondre","⚔"],["Personnages","♙"],["Civilisations","♜"],["Régions","⌁"]];
 return <main className="game"><header className="top"><div className="brand">✦ ARTHENIS <small>WHERE WORLDS ARE BORN</small></div><div className="worldHead"><b>{title}</b><span>● MONDE VIVANT · JOUR {day}</span></div><button className="primary" onClick={advance}>▶ Continuer</button></header>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice("")}>×</button></div>}<div className="hud"><aside className="side">{menu.map(([label,icon])=><button key={label} className={tab===label?"selected":""} onClick={()=>setTab(label)}><i>{icon}</i><span>{label}</span></button>)}<div className="sideBottom"><small>SIMULATION</small><button onClick={advance}>⏩ Avancer le temps</button></div></aside><section className="board"><div className="boardTop"><div><small>CARTE DU MONDE</small><h2>{title}</h2></div><div className="stats">{stats.map(s=><span key={s.l}><b>{s.n}</b>{s.l}</span>)}</div></div>

 {tab==="Carte"&&<><div className="gameMap"><div className="mapMist"/><div className="continent c1"/><div className="continent c2"/><div className="continent c3"/><div className="river r1"/><div className="river r2"/>{regions.map((r,i)=>{const p=mapPoint(r.id,i);return <button className="marker regionMarker" style={p} key={r.id} onClick={()=>setNotice("⌁ "+r.name+" · "+r.state)}><b>◈</b><span>{r.name}</span></button>})}{civs.map((c,i)=>{const p=mapPoint(c.id,i+3);return <button className="marker civMarker" style={p} key={c.id} onClick={()=>setNotice("♜ "+c.name+" · "+c.description)}><b>♜</b><span>{c.name}</span></button>})}{chars.map((c,i)=>{const p=mapPoint(c.id,i+9);return <button className="marker charMarker" style={p} key={c.id} onClick={()=>setNotice("♙ "+c.name+" · "+c.goal)}><b>♙</b><span>{c.name}</span></button>})}{!regions.length&&!civs.length&&!chars.length&&<div className="emptyMap">TON MONDE EST ENCORE VIDE<br/><small>Ajoute une région, une civilisation ou un personnage : il apparaîtra ici immédiatement.</small></div>}</div><div className="actionDock"><button onClick={()=>setTab("Ajouter")}>＋ Ajouter au monde</button><button onClick={()=>setTab("Régions")}>⌁ Région</button><button onClick={()=>setTab("Civilisations")}>♜ Civilisation</button><button onClick={()=>setTab("Personnages")}>♙ Personnage</button></div></>}

 {tab==="Régions"&&<Panel title="Ajouter une région" subtitle="Elle apparaît immédiatement sur la carte."><input value={regionName} onChange={e=>setRegionName(e.target.value)} placeholder="Nom de la région"/><button className="primary" onClick={createRegion}>Créer et placer sur la carte →</button><List items={regions.map(r=>({title:r.name,text:r.state}))}/></Panel>}
 {tab==="Civilisations"&&<Panel title="Fonder une civilisation" subtitle="Une civilisation existe parce que tu l'as créée ou parce qu'une évolution logique du monde l'a justifiée."><input value={civName} onChange={e=>setCivName(e.target.value)} placeholder="Nom de la civilisation"/><textarea value={civDescription} onChange={e=>setCivDescription(e.target.value)} placeholder="Description, culture, identité…"/><button className="primary" onClick={createCiv}>Fonder et afficher sur la carte →</button><List items={civs.map(c=>({title:c.name,text:c.description}))}/></Panel>}
 {tab==="Personnages"&&<Panel title="Acteurs du monde" subtitle="Aucun personnage n'est généré au hasard. Ils sont créés par toi, ajoutés comme PNJ volontairement, ou naissent d'une descendance."><div className="npcSwitch"><b>PNJ optionnels</b><button onClick={()=>setAllowNPC(!allowNPC)}>{allowNPC?"✓ PNJ autorisés":"Autoriser les PNJ"}</button></div>{allowNPC&&<div className="miniForm"><input value={npcName} onChange={e=>setNpcName(e.target.value)} placeholder="Nom du PNJ"/><input value={npcRole} onChange={e=>setNpcRole(e.target.value)} placeholder="Rôle / objectif"/><button onClick={createNPC}>Ajouter le PNJ</button></div>}<div className="formGrid"><input value={charName} onChange={e=>setCharName(e.target.value)} placeholder="Nom"/><input value={charDescription} onChange={e=>setCharDescription(e.target.value)} placeholder="Description"/><select value={charCiv} onChange={e=>setCharCiv(e.target.value)}><option value="">Sans civilisation</option>{civs.map(c=><option key={c.id}>{c.name}</option>)}</select><select value={charRegion} onChange={e=>setCharRegion(e.target.value)}><option value="">Sans région</option>{regions.map(r=><option key={r.id}>{r.name}</option>)}</select><input value={charPower} onChange={e=>setCharPower(e.target.value)} placeholder="Pouvoir / influence"/><input value={charGoal} onChange={e=>setCharGoal(e.target.value)} placeholder="Objectif"/></div><button className="primary" onClick={createChar}>Créer le personnage →</button><div className="birth"><b>👶 Descendance</b><select value={parentA} onChange={e=>setParentA(e.target.value)}><option value="">Premier parent</option>{chars.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select value={parentB} onChange={e=>setParentB(e.target.value)}><option value="">Second parent</option>{chars.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><input value={childName} onChange={e=>setChildName(e.target.value)} placeholder="Nom de l'enfant"/><button onClick={createChild}>Faire naître l'enfant</button></div><List items={chars.map(c=>({title:c.name,text:(c.origin==="birth"?"Né dans le monde · ":"Créé par le créateur · ")+c.goal}))}/></Panel>}
 {tab==="Ajouter"&&<Panel title="Créer une nouvelle influence" subtitle="L'ajout entre immédiatement dans la chronologie. Ses conséquences, elles, peuvent rester inconnues jusqu'à l'avancée du temps."><textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Décris l'événement, la découverte, la ressource ou le changement…"/><button className="primary" onClick={addEvent}>Créer l'influence →</button></Panel>}
 {tab==="Répondre"&&<Panel title="Répondre à une conséquence" subtitle="Tu ne supprimes pas le passé. Tu ajoutes une nouvelle cause pour tenter de transformer le futur."><select value={responseTarget} onChange={e=>setResponseTarget(e.target.value)}><option value="">Choisir une conséquence de la chronologie</option>{events.map(e=><option value={String(e.id)} key={e.id}>Jour {e.day} · {e.text}</option>)}</select><textarea value={responseIdea} onChange={e=>setResponseIdea(e.target.value)} placeholder="Décris la contre-influence…"/><button className="primary" onClick={createResponse}>Vérifier et créer →</button></Panel>}
 {tab==="Chronologie"&&<Panel title="Chronologie permanente" subtitle="Rien n'est supprimé. Chaque cause devient une partie de l'histoire."><div className="timeline">{events.map(e=><div className="timelineItem" key={e.id}><b>JOUR {e.day}</b><p>{e.text}</p><span>{e.impact}</span></div>)}{!events.length&&<div className="emptyPanel">Le monde vient de naître. Son histoire attend ton premier choix.</div>}</div><div className="hiddenCount">◌ {consequences.length} conséquence(s) encore inconnue(s)</div></Panel>}
 </section><aside className="intel"><small>ACTIVITÉ DU MONDE</small><div className="intelDay">JOUR {day}</div><p>Le monde n'invente pas de personnages sans ta permission. Il évolue uniquement à partir de ce qui existe déjà.</p><div className="intelFeed">{events.slice(0,5).map(e=><div key={e.id}><b>Jour {e.day}</b>{e.text}</div>)}</div><button className="primary wide" onClick={advance}>Continuer l'histoire →</button></aside></div></main>;
}

function Panel({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="panel"><p className="panelTag">COMMANDE DU CRÉATEUR</p><h2>{title}</h2><p className="panelSub">{subtitle}</p>{children}</div>}
function List({items}:{items:{title:string;text:string}[]}){return <div className="cards">{items.map((x,i)=><div className="worldCard" key={i}><b>{x.title}</b><span>{x.text}</span></div>)}</div>}
