import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { OPENAI_TEXT_MODEL } from "../../../lib/ai/config";
const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://kqymkheiildnbqaksdlx.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY??"";
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const ACTIONS=new Set(["advance","member-upsert","member-remove","rule-update","proposal"]);const ROLES=new Set(["admin","creator","contributor","viewer"]);const PROPOSAL_TYPES=new Set(["Région","Civilisation","Village","Personnage","Créature","Influence"]);
function clientFor(request:Request){const authorization=request.headers.get("authorization");return createClient(supabaseUrl,supabaseKey,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:authorization?{Authorization:authorization}:{}}});}
function jsonError(message:string,status=400){return NextResponse.json({error:message},{status});}
async function requireUser(supabase:ReturnType<typeof clientFor>){const {data,error}=await supabase.auth.getUser();if(error||!data.user)throw new Error("Authentification requise.");return data.user;}
async function canManageMembers(supabase:ReturnType<typeof clientFor>,worldId:string,userId:string){const {data:world}=await supabase.from("worlds").select("owner_id").eq("id",worldId).single();if(world?.owner_id===userId)return true;const {data:m}=await supabase.from("world_members").select("role").eq("world_id",worldId).eq("user_id",userId).single();return m?.role==="admin";}
async function canAdvance(supabase:ReturnType<typeof clientFor>,worldId:string,userId:string){const {data:world}=await supabase.from("worlds").select("owner_id").eq("id",worldId).single();if(world?.owner_id===userId)return true;const {data:m}=await supabase.from("world_members").select("role").eq("world_id",worldId).eq("user_id",userId).single();return m?.role==="admin"||m?.role==="creator";}
export async function POST(request:Request){const supabase=clientFor(request);try{const user=await requireUser(supabase);const body=await request.json().catch(()=>null);if(!body||typeof body!=="object"||Array.isArray(body))return jsonError("Requête invalide.");if(typeof body.worldId!=="string"||!UUID_RE.test(body.worldId))return jsonError("Identifiant de monde invalide.");if(typeof body.action!=="string"||!ACTIONS.has(body.action))return jsonError("Action inconnue.");const worldId=body.worldId,action=body.action;
if(action==="advance"){if(!(await canAdvance(supabase,worldId,user.id)))return jsonError("Seul le propriétaire, un administrateur ou un créateur peut faire évoluer le monde.",403);const {data:world,error:worldError}=await supabase.from("worlds").select("id,name,theme,world_memory,fiction_enabled,fictional_creatures_enabled,magic_enabled").eq("id",worldId).single();if(worldError||!world)return jsonError("Monde introuvable ou accès refusé.",404);const previousDay=Number((world.world_memory as Record<string,unknown>|null)?.day??1);const nextDay=Number.isFinite(previousDay)&&previousDay>=1?Math.floor(previousDay)+1:2;const {count:regionCount}=await supabase.from("regions").select("id",{count:"exact",head:true}).eq("world_id",worldId);const {count:civilizationCount}=await supabase.from("civilizations").select("id",{count:"exact",head:true}).eq("world_id",worldId);const {count:creatureCount}=await supabase.from("creatures").select("id",{count:"exact",head:true}).eq("world_id",worldId);let title=`Évolution du monde — Jour ${nextDay}`;let description=`Le passage du temps transforme progressivement ${world.name}. Les territoires, sociétés et créatures continuent d'évoluer selon les règles établies.`;let consequences=[`Le monde entre dans son jour ${nextDay}.`,`${regionCount??0} région(s), ${civilizationCount??0} civilisation(s) et ${creatureCount??0} créature(s) sont actuellement enregistrées.`];const apiKey=process.env.OPENAI_API_KEY;if(apiKey){const prompt=`Tu es le moteur d'évolution d'Arthenis. Génère un événement cohérent et sobre pour le jour ${nextDay} du monde "${world.name}". Thème: ${world.theme}. Fiction: ${world.fiction_enabled}. Créatures fictives: ${world.fictional_creatures_enabled}. Magie: ${world.magic_enabled}. Ne crée aucune technologie moderne ou élément surréaliste non autorisé. Réponds uniquement en JSON: {"title":"...","description":"...","consequences":["...","..."]}.`;const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:OPENAI_TEXT_MODEL,input:prompt,max_output_tokens:500})});if(response.ok){const upstream=await response.json().catch(()=>null);const text=upstream?.output_text;if(typeof text==="string"){try{const generated=JSON.parse(text);if(typeof generated?.title==="string"&&typeof generated?.description==="string"&&Array.isArray(generated?.consequences)){title=generated.title.trim().slice(0,180)||title;description=generated.description.trim().slice(0,1200)||description;consequences=generated.consequences.filter((item:unknown):item is string=>typeof item==="string"&&item.trim().length>0).map(item=>item.trim().slice(0,500)).slice(0,6);}}catch{}}}}
const {data:event,error:eventError}=await supabase.from("timeline_events").insert({world_id:worldId,title,description,world_day:nextDay,consequences}).select().single();if(eventError)return jsonError("Impossible d'enregistrer l'évolution du monde.",500);
const stamp={day:nextDay,event_id:event.id,event:title};const [rg,cv,ch,cr]=await Promise.all([supabase.from("regions").select("id,facts").eq("world_id",worldId).order("created_at").limit(1).maybeSingle(),supabase.from("civilizations").select("id,facts").eq("world_id",worldId).order("created_at").limit(1).maybeSingle(),supabase.from("characters").select("id,facts").eq("world_id",worldId).order("created_at").limit(1).maybeSingle(),supabase.from("creatures").select("id,facts").eq("world_id",worldId).order("created_at").limit(1).maybeSingle()]);
const updates=[rg.data&&supabase.from("regions").update({facts:{...(rg.data.facts&&typeof rg.data.facts==="object"?rg.data.facts:{}),last_evolution:stamp}}).eq("id",rg.data.id).eq("world_id",worldId),cv.data&&supabase.from("civilizations").update({facts:{...(cv.data.facts&&typeof cv.data.facts==="object"?cv.data.facts:{}),last_evolution:stamp}}).eq("id",cv.data.id).eq("world_id",worldId),ch.data&&supabase.from("characters").update({facts:{...(ch.data.facts&&typeof ch.data.facts==="object"?ch.data.facts:{}),last_evolution:stamp}}).eq("id",ch.data.id).eq("world_id",worldId),cr.data&&supabase.from("creatures").update({facts:{...(cr.data.facts&&typeof cr.data.facts==="object"?cr.data.facts:{}),last_evolution:stamp}}).eq("id",cr.data.id).eq("world_id",worldId)].filter(Boolean);await Promise.all(updates);
const {error:updateError}=await supabase.from("worlds").update({world_memory:{...(world.world_memory??{}),day:nextDay,map_version:Number((world.world_memory as any)?.map_version||0)+1,last_event_id:event.id},updated_at:new Date().toISOString()}).eq("id",worldId);if(updateError)return jsonError("L'événement a été créé, mais le jour n'a pas pu être sauvegardé.",500);return NextResponse.json({day:nextDay,event});}
if(action==="member-upsert"){if(typeof body.userId!=="string"||!UUID_RE.test(body.userId))return jsonError("Identifiant utilisateur invalide.");if(!(await canManageMembers(supabase,worldId,user.id)))return jsonError("Seul le propriétaire ou un administrateur peut gérer les membres.",403);if(body.userId===user.id)return jsonError("Le propriétaire ne peut pas se retirer lui-même via cette action.");const role=typeof body.role==="string"&&ROLES.has(body.role)?body.role:"viewer";const permissions=body.permissions&&typeof body.permissions==="object"&&!Array.isArray(body.permissions)?body.permissions:{};const {data,error}=await supabase.from("world_members").upsert({world_id:worldId,user_id:body.userId,role,permissions},{onConflict:"world_id,user_id"}).select().single();if(error)return jsonError("Impossible de modifier l'autorisation du membre.",403);return NextResponse.json({member:data});}
if(action==="member-remove"){if(typeof body.userId!=="string"||!UUID_RE.test(body.userId))return jsonError("Identifiant utilisateur invalide.");if(!(await canManageMembers(supabase,worldId,user.id)))return jsonError("Seul le propriétaire ou un administrateur peut gérer les membres.",403);if(body.userId===user.id)return jsonError("Le propriétaire ne peut pas se retirer lui-même via cette action.");const {error}=await supabase.from("world_members").delete().eq("world_id",worldId).eq("user_id",body.userId);if(error)return jsonError("Impossible de retirer ce membre.",403);return NextResponse.json({ok:true});}
if(action==="rule-update"){if(typeof body.ruleId!=="string"||!UUID_RE.test(body.ruleId)||typeof body.title!=="string"||typeof body.description!=="string")return jsonError("Données de règle invalides.");const title=body.title.trim().slice(0,160),ruleDescription=body.description.trim().slice(0,1200);if(!title||!ruleDescription)return jsonError("Le titre et la description de la règle sont requis.");const {data:existing}=await supabase.from("world_rules").select("immutable").eq("id",body.ruleId).eq("world_id",worldId).single();if(!existing)return jsonError("Règle introuvable.",404);if(existing.immutable)return jsonError("Cette loi fondamentale est immuable.",403);const {data,error}=await supabase.from("world_rules").update({title,description:ruleDescription}).eq("id",body.ruleId).eq("world_id",worldId).select().single();if(error)return jsonError("Impossible de modifier cette règle.",403);return NextResponse.json({rule:data});}
if(action==="proposal"){const type=typeof body.type==="string"&&PROPOSAL_TYPES.has(body.type)?body.type:null;if(!type)return jsonError("Type de proposition invalide.");const payload=body.payload&&typeof body.payload==="object"&&!Array.isArray(body.payload)?body.payload:{};const coherenceResult=body.coherenceResult&&typeof body.coherenceResult==="object"&&!Array.isArray(body.coherenceResult)?body.coherenceResult:{};const coherenceStatus=body.coherenceStatus==="rejected"?"rejected":"accepted";const {data,error}=await supabase.from("creation_proposals").insert({world_id:worldId,author_id:user.id,type,payload,coherence_status:coherenceStatus,coherence_result:coherenceResult}).select().single();if(error)return jsonError("Impossible d'enregistrer la proposition.",403);return NextResponse.json({proposal:data});}return jsonError("Action inconnue.");}catch(error){return jsonError(error instanceof Error?error.message:"Erreur interne.",401);}}
