import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://kqymkheiildnbqaksdlx.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY??"";
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const ACTIONS=new Set(["advance","member-upsert","member-remove","rule-update","proposal"]);
const ROLES=new Set(["admin","creator","contributor","viewer"]);
const PROPOSAL_TYPES=new Set(["Région","Civilisation","Village","Personnage","Créature","Influence"]);
function clientFor(request:Request){const authorization=request.headers.get("authorization");return createClient(supabaseUrl,supabaseKey,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:authorization?{Authorization:authorization}:{}}});}
function jsonError(message:string,status=400){return NextResponse.json({error:message},{status});}
async function requireUser(supabase:ReturnType<typeof clientFor>){const {data,error}=await supabase.auth.getUser();if(error||!data.user)throw new Error("Authentification requise.");return data.user;}
async function canManageMembers(supabase:ReturnType<typeof clientFor>,worldId:string,userId:string){const {data:world}=await supabase.from("worlds").select("owner_id").eq("id",worldId).single();if(world?.owner_id===userId)return true;const {data:m}=await supabase.from("world_members").select("role").eq("world_id",worldId).eq("user_id",userId).single();return m?.role==="admin";}
function safeString(v:unknown,max:number){return typeof v==="string"?v.trim().slice(0,max):"";}

export async function POST(request:Request){const supabase=clientFor(request);try{const user=await requireUser(supabase);const body=await request.json().catch(()=>null);if(!body||typeof body!=="object"||Array.isArray(body))return jsonError("Requête invalide.");if(typeof body.worldId!=="string"||!UUID_RE.test(body.worldId))return jsonError("Identifiant de monde invalide.");if(typeof body.action!=="string"||!ACTIONS.has(body.action))return jsonError("Action inconnue.");const worldId=body.worldId,action=body.action;
 if(action==="advance"){
  const {data:world,error:we}=await supabase.from("worlds").select("id,name,theme,world_memory,fiction_enabled,fictional_creatures_enabled,magic_enabled,visual_bible").eq("id",worldId).single();if(we||!world)return jsonError("Monde introuvable ou accès refusé.",404);
  const {data:nextDay,error:ae}=await supabase.rpc("advance_world_day",{p_world:worldId});if(ae||typeof nextDay!=="number")return jsonError("Impossible de faire avancer le monde de façon sécurisée.",500);
  const [{data:regions},{data:civilizations},{data:characters},{data:creatures}]=await Promise.all([
   supabase.from("regions").select("id,name,description,facts,resources,biome").eq("world_id",worldId).limit(40),
   supabase.from("civilizations").select("id,name,description,facts,culture,technology_level").eq("world_id",worldId).limit(40),
   supabase.from("characters").select("id,name,biography,facts,role,profession,magic_level").eq("world_id",worldId).limit(40),
   supabase.from("creatures").select("id,name,description,facts,fictional,classification").eq("world_id",worldId).limit(40)
  ]);
  let title=`Évolution du monde — Jour ${nextDay}`;let description=`Le passage du temps transforme progressivement ${world.name}. Les territoires, sociétés, personnages et créatures évoluent selon les règles établies.`;let consequences=[`Le monde entre dans son jour ${nextDay}.`,`Les conséquences respectent les lois de ${world.name}.`];let updates:any[]=[];
  const apiKey=process.env.OPENAI_API_KEY;
  if(apiKey){const prompt=`Tu es le World Engine d'Arthenis. Fais évoluer uniquement des entités EXISTANTES du monde, sans en créer de nouvelles. Monde=${world.name}; thème=${world.theme}; fiction=${world.fiction_enabled}; créatures fictives=${world.fictional_creatures_enabled}; magie=${world.magic_enabled}. Jour=${nextDay}. Ne jamais introduire technologie moderne, surréalisme ou magie si interdits. Choisis au maximum 3 entités et donne de petites conséquences cohérentes. Réponds uniquement JSON: {"title":"","description":"","consequences":[""],"updates":[{"type":"region|civilization|character|creature","id":"UUID","description":"nouvelle description courte","fact":"nouveau fait historique"}]}. Entités: ${JSON.stringify({regions,civilizations,characters,creatures})}`;
   const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:"gpt-5.6-luna",input:prompt,max_output_tokens:1200})});
   if(response.ok){const out=await response.json().catch(()=>null);if(typeof out?.output_text==="string"){try{const g=JSON.parse(out.output_text);if(typeof g?.title==="string")title=safeString(g.title,180)||title;if(typeof g?.description==="string")description=safeString(g.description,1200)||description;if(Array.isArray(g?.consequences))consequences=g.consequences.filter((x:unknown):x is string=>typeof x==="string"&&x.trim()).map(x=>x.trim().slice(0,500)).slice(0,6);if(Array.isArray(g?.updates))updates=g.updates.filter((u:any)=>u&&typeof u==="object"&&UUID_RE.test(u.id)&&["region","civilization","character","creature"].includes(u.type)).slice(0,3);}catch{}}}
  }
  const entityMap={region:new Map((regions??[]).map(x=>[x.id,x])),civilization:new Map((civilizations??[]).map(x=>[x.id,x])),character:new Map((characters??[]).map(x=>[x.id,x])),creature:new Map((creatures??[]).map(x=>[x.id,x]))};
  const applied:any[]=[];
  for(const u of updates){const current=entityMap[u.type as keyof typeof entityMap]?.get(u.id);if(!current)continue;const table=u.type==="region"?"regions":u.type==="civilization"?"civilizations":u.type==="character"?"characters":"creatures";const text=safeString(u.description,1200);const fact=safeString(u.fact,500);if(!text&&!fact)continue;const patch:any={};if(u.type==="character")patch.biography=text||current.biography;else patch.description=text||current.description;if(fact)patch.facts={...(current.facts&&typeof current.facts==="object"?current.facts:{}),last_evolution:{day:nextDay,fact}};const {error}=await supabase.from(table).update(patch).eq("id",u.id).eq("world_id",worldId);if(!error)applied.push({type:u.type,id:u.id,fact});}
  consequences=[...consequences,...applied.map(a=>`${a.type} ${a.id} a évolué.`)];
  const {data:event,error:eventError}=await supabase.from("timeline_events").insert({world_id:worldId,title,description,world_day:nextDay,consequences}).select().single();if(eventError)return jsonError("L'évolution a été calculée mais l'événement n'a pas pu être enregistré.",500);
  const memory={...(world.world_memory&&typeof world.world_memory==="object"?world.world_memory:{}),day:nextDay,map_version:Number((world.world_memory as any)?.map_version||0)+1,last_event_id:event.id};await supabase.from("worlds").update({world_memory:memory,updated_at:new Date().toISOString()}).eq("id",worldId);
  return NextResponse.json({day:nextDay,event,updates:applied,mapVersion:memory.map_version});
 }
 if(action==="member-upsert"){if(typeof body.userId!=="string"||!UUID_RE.test(body.userId))return jsonError("Identifiant utilisateur invalide.");if(!(await canManageMembers(supabase,worldId,user.id)))return jsonError("Seul le propriétaire ou un administrateur peut gérer les membres.",403);if(body.userId===user.id)return jsonError("Le propriétaire ne peut pas se retirer lui-même via cette action.");const role=typeof body.role==="string"&&ROLES.has(body.role)?body.role:"viewer";const permissions=body.permissions&&typeof body.permissions==="object"&&!Array.isArray(body.permissions)?body.permissions:{};const {data,error}=await supabase.from("world_members").upsert({world_id:worldId,user_id:body.userId,role,permissions},{onConflict:"world_id,user_id"}).select().single();if(error)return jsonError("Impossible de modifier l'autorisation du membre.",403);return NextResponse.json({member:data});}
 if(action==="member-remove"){if(typeof body.userId!=="string"||!UUID_RE.test(body.userId))return jsonError("Identifiant utilisateur invalide.");if(!(await canManageMembers(supabase,worldId,user.id)))return jsonError("Seul le propriétaire ou un administrateur peut gérer les membres.",403);if(body.userId===user.id)return jsonError("Le propriétaire ne peut pas se retirer lui-même via cette action.");const {error}=await supabase.from("world_members").delete().eq("world_id",worldId).eq("user_id",body.userId);if(error)return jsonError("Impossible de retirer ce membre.",403);return NextResponse.json({ok:true});}
 if(action==="rule-update"){if(typeof body.ruleId!=="string"||!UUID_RE.test(body.ruleId)||typeof body.title!=="string"||typeof body.description!=="string")return jsonError("Données de règle invalides.");const title=safeString(body.title,160),description=safeString(body.description,1200);if(!title||!description)return jsonError("Le titre et la description de la règle sont requis.");const {data:existing}=await supabase.from("world_rules").select("immutable").eq("id",body.ruleId).eq("world_id",worldId).single();if(!existing)return jsonError("Règle introuvable.",404);if(existing.immutable)return jsonError("Cette loi fondamentale est immuable.",403);const {data,error}=await supabase.from("world_rules").update({title,description}).eq("id",body.ruleId).eq("world_id",worldId).select().single();if(error)return jsonError("Impossible de modifier cette règle.",403);return NextResponse.json({rule:data});}
 if(action==="proposal"){const type=typeof body.type==="string"&&PROPOSAL_TYPES.has(body.type)?body.type:null;if(!type)return jsonError("Type de proposition invalide.");const payload=body.payload&&typeof body.payload==="object"&&!Array.isArray(body.payload)?body.payload:{};const coherenceResult=body.coherenceResult&&typeof body.coherenceResult==="object"&&!Array.isArray(body.coherenceResult)?body.coherenceResult:{};const coherenceStatus=body.coherenceStatus==="rejected"?"rejected":"accepted";const {data,error}=await supabase.from("creation_proposals").insert({world_id:worldId,author_id:user.id,type,payload,coherence_status:coherenceStatus,coherence_result:coherenceResult}).select().single();if(error)return jsonError("Impossible d'enregistrer la proposition.",403);return NextResponse.json({proposal:data});}
 return jsonError("Action inconnue.");
 }catch(error){return jsonError(error instanceof Error?error.message:"Erreur interne.",401);}}
